name: build wax220

on:
  push:
    branches:
      - 'wax220'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget
      - name: Update the feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Copy config
        run: cp wax220.buildinfo .config
      - name: Build
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        run: make -j$(nproc) defconfig download clean world
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: bin/targets/mediatek/filogic
